version: 2
jobs:
  build:
    docker:
      - image: circleci/build-image
    branches:
      only:
        - master
    working_directory: ~/repo

    steps:
      - checkout
      - run:
          name: build rpm
          command: make