version: 2
jobs:
  build:
    docker:
      - image: buildpack-deps:trusty
    branches:
      only:
        - master
    working_directory: ~/repo

    steps:
      - checkout
      - run:
          name: build rpm
          command: make