version: 2
jobs:
  build:
    docker:
      - image: docker:17.05.0-ce-git
    branches:
      only:
        - master
    working_directory: ~/repo

    steps:
      - checkout
      - run:
          name: build rpm
          command: make
